# Generated by Django 5.0.1 on 2024-02-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
