# Generated by Django 5.0.1 on 2024-02-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_policia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policia',
        ),
    ]
