# Generated by Django 5.0.1 on 2024-02-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_policia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infraccion',
        ),
    ]
