# Generated by Django 5.0.1 on 2024-02-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_infraccion_oficial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infraccion',
        ),
    ]
